name: bloc
description: "A simple imeplementation of bloc for Flutter"
version: 0.0.1
homepage: https://github.com/tihrasguinho/common

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
